language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS test_db;'
  - mysql -e 'CREATE DATABASE test_db;'
after_sucess:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
