language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
  - sudo apt-get update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'
after_sucess:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
